name: Build README
on:
  schedule:
    - cron: '0 23 * * *'
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.9.1
      - name: Install dependencies
        uses: tj-actions/puppeteer@v3.2
        with:
          args: yarn install
      - name: Update user directory
        uses: tj-actions/puppeteer@v3.2
        with:
          args: yarn start
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "-04:00"
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "me@shu.nu"
          git config --global user.name "shun-ueda"
          git add -A
          git commit -m "${{ steps.current-time.outputs.readableTime }}" || exit 0
          git push
